export const e2eTestIds = {
  project: {
    empty: 'project.empty',
    selector: 'project.selector',
    directories: {
      trigger: 'project.directories.trigger',
      dialog: 'project.directories.dialog',
      list: 'project.directories.list',
      empty: 'project.directories.empty',
      link: 'project.directories.link',
      linkError: 'project.directories.link-error',
      unlink: 'project.directories.unlink',
      unlinkError: 'project.directories.unlink-error',
    },
    create: {
      emptyTrigger: 'project.create.empty-trigger',
      workspaceTrigger: 'project.create.workspace-trigger',
      dialog: 'project.create.dialog',
      form: 'project.create.form',
      name: 'project.create.name',
      key: 'project.create.key',
      directory: 'project.create.directory',
      selectDirectory: 'project.create.select-directory',
      clearDirectory: 'project.create.clear-directory',
      cancel: 'project.create.cancel',
      submit: 'project.create.submit',
      error: 'project.create.error',
    },
  },
}
