export const e2eTestIds = {
  ticket: {
    reference: 'ticket.reference',
    create: {
      title: 'ticket.create.title',
      submit: 'ticket.create.submit',
    },
  },
  project: {
    empty: 'project.empty',
    selector: 'project.selector',
    directories: {
      trigger: 'project.directories.trigger',
      dialog: 'project.directories.dialog',
      list: 'project.directories.list',
      empty: 'project.directories.empty',
      link: 'project.directories.link',
      linkError: 'project.directories.link-error',
      unlink: 'project.directories.unlink',
      unlinkError: 'project.directories.unlink-error',
    },
    create: {
      emptyTrigger: 'project.create.empty-trigger',
      workspaceTrigger: 'project.create.workspace-trigger',
      dialog: 'project.create.dialog',
      form: 'project.create.form',
      name: 'project.create.name',
      key: 'project.create.key',
      directory: 'project.create.directory',
      selectDirectory: 'project.create.select-directory',
      clearDirectory: 'project.create.clear-directory',
      cancel: 'project.create.cancel',
      submit: 'project.create.submit',
      error: 'project.create.error',
    },
    archive: {
      trigger: 'project.archive.trigger',
      dialog: 'project.archive.dialog',
      cancel: 'project.archive.cancel',
      confirm: 'project.archive.confirm',
      error: 'project.archive.error',
    },
    archived: {
      emptyTrigger: 'project.archived.empty-trigger',
      workspaceTrigger: 'project.archived.workspace-trigger',
      screen: 'project.archived.screen',
      list: 'project.archived.list',
      empty: 'project.archived.empty',
      restore: 'project.archived.restore',
      error: 'project.archived.error',
    },
  },
}
