packages:
  - packages/*

nodeLinker: hoisted

overrides:
  '@electron/node-gyp': 10.2.0-electron.2
  extract-zip: npm:@electron-internal/extract-zip@1.0.5

allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
  lightningcss: true
  msgpackr-extract: true
  sharp: true

minimumReleaseAgeExclude:
  - '@effect/platform-browser@4.0.0-beta.103'
  - effect@4.0.0-beta.103
  - '@effect/vitest@4.0.0-beta.103'
  - '@tanstack/router-core@1.171.16'
  - '@tanstack/router-generator@1.167.22'
  - '@tanstack/router-plugin@1.168.24'
  - electron@43.3.0
  - '@effect/tsgo-darwin-arm64@0.31.0'
  - '@effect/tsgo-darwin-x64@0.31.0'
  - '@effect/tsgo-linux-arm64@0.31.0'
  - '@effect/tsgo-linux-arm@0.31.0'
  - '@effect/tsgo-linux-x64@0.31.0'
  - '@effect/tsgo-win32-arm64@0.31.0'
  - '@effect/tsgo-win32-x64@0.31.0'
  - '@effect/tsgo@0.31.0'
