packages:
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  lightningcss: true
  msgpackr-extract: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@effect/platform-browser@4.0.0-beta.103'
  - effect@4.0.0-beta.103
  - '@effect/vitest@4.0.0-beta.103'
