/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsArchivedRouteImport } from './routes/projects.archived'
import { Route as ProjectsProjectIdTicketsRouteImport } from './routes/projects.$projectId.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsArchivedRoute = ProjectsArchivedRouteImport.update({
  id: '/projects/archived',
  path: '/projects/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTicketsRoute =
  ProjectsProjectIdTicketsRouteImport.update({
    id: '/projects/$projectId/tickets',
    path: '/projects/$projectId/tickets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/archived': typeof ProjectsArchivedRoute
  '/projects/$projectId/tickets': typeof ProjectsProjectIdTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/archived': typeof ProjectsArchivedRoute
  '/projects/$projectId/tickets': typeof ProjectsProjectIdTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/archived': typeof ProjectsArchivedRoute
  '/projects/$projectId/tickets': typeof ProjectsProjectIdTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/archived' | '/projects/$projectId/tickets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/archived' | '/projects/$projectId/tickets'
  id: '__root__' | '/' | '/projects/archived' | '/projects/$projectId/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsArchivedRoute: typeof ProjectsArchivedRoute
  ProjectsProjectIdTicketsRoute: typeof ProjectsProjectIdTicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/archived': {
      id: '/projects/archived'
      path: '/projects/archived'
      fullPath: '/projects/archived'
      preLoaderRoute: typeof ProjectsArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tickets': {
      id: '/projects/$projectId/tickets'
      path: '/projects/$projectId/tickets'
      fullPath: '/projects/$projectId/tickets'
      preLoaderRoute: typeof ProjectsProjectIdTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsArchivedRoute: ProjectsArchivedRoute,
  ProjectsProjectIdTicketsRoute: ProjectsProjectIdTicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
